name: Kustomize yaml validation
description: "Github Action that validates yaml and kustomization outputs with yq and kubeconform"
branding:
  icon: align-justify
  color: blue
inputs:
  kubeconform-verbose:
    description: "Boolean variable to run kubeconform checks with additonal logs"
    required: true
    default: "false"
  flux-dir:
    description: "Root directory of the flux installation, default is ./clusters"
    required: true
    default: "./clusters"
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: validate.sh ${{ inputs.kubeconform-verbose }} ${{ inputs.flux-dir }}
      shell: bash
